### ISSUE TITLE
Fresh Docker Installation: Unable to open database file

### ISSUE THREAD

**Issue by EthanC** [TheLovinator1/discord-rss-bot#97]
Following the setup instructions provided in the README, it appears this project is not ready to go out of the box. It seems to be attempting to locate a `db.sqlite` file in the volume on the host machine that does not exist. I attempted to create an empty SQLite database and place it in this location, but it did not resolve the issue.

Perhaps if the db does not exist, it should handle creating a new one? Or is there a missing step in the initial setup?

```py
Data is stored in '/home/botuser/.local/share/discord_rss_bot'.
Traceback (most recent call last):
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/reader/_sqlite_utils.py", line 101, in wrap_exceptions

d
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/reader/_storage.py", line 412, in __init__
    self.factory = LocalConnectionFactory(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/reader/_sqlite_utils.py", line 460, in __init__
    self.__call__()
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/reader/_sqlite_utils.py", line 480, in __call__
    self._local.db = db = sqlite3.connect(self.path, **self.kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/botuser/discord-rss-bot/discord_rss_bot/main.py", line 20, in <module>
    from discord_rss_bot.custom_filters import encode_url, entry_is_blacklisted, entry_is_whitelisted
  File "/home/botuser/discord-rss-bot/discord_rss_bot/custom_filters.py", line 11, in <module>
    reader: Reader = get_reader()
                     ^^^^^^^^^^^^
  File "/home/botuser/discord-rss-bot/discord_rss_bot/settings.py", line 32, in get_reader
    return make_reader(url=str(db_location))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/reader/core.py", line 253, in make_reader
    storage = _storage or Storage(url, factory=_storage_factory)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/reader/_storage.py", line 411, in __init__
    with wrap_exceptions(StorageError, "error while opening database"):
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/botuser/.cache/pypoetry/virtualenvs/discord-rss-bot-dhsCdbBF-py3.11/lib/python3.11/site-packages/reader/_sqlite_utils.py", line 104, in wrap_exceptions
    raise exc_type(message) from e
reader.exceptions.StorageError: error while opening database: sqlite3.OperationalError: unable to open database file
```

**Comment by TheLovinator1** [comment]
Hi, it already creates all the folders and the database automatically so it should work for you.

It could be because I am changing the user in the Dockerfile to a non-root user [here ](https://github.com/TheLovinator1/discord-rss-bot/blob/master/Dockerfile#L22)? Who owns the volume on the host machine?

**Comment by EthanC** [comment]
Ah, good call! The folder created on the local machine is owned by `root` with `rwxr-xr-x` (`0755`) permissions.

I changed this to my user account using `chown` and it indeed fixed the issue.
